### ISSUE TITLE
Using in non Rails app or gem

### ISSUE THREAD

**Issue by sleepingstu** [tombell/minitest-osx#3]
Have started using this gem in all my projects (because it's awesome!) but wanted to see if there is a better way to us this in non Rails app/gems than what I am currently doing.

To get this to work in a non Rails gem I'm having to add `require "active_support/all"` to the `test_helper.rb` file because of the use of `cattr_accessor` in the `OsxNotificationReporter` class.

So I was wondering is there a way that the class could be set up with the use of the `cattr_accessor` so that there isn't a dependency of Active Support?

**Comment by sleepingstu** [comment]
Actually just to follow on...

Adding `require "active_support/all"` means that I don't get an error about `cattr_accessor` but the notifications themselves don't work (as in appear) as expected.

**Comment by tombell** [comment]
Ah `cattr_accessor` appears to be a Rails thing (https://apidock.com/rails/Class/cattr_accessor), I didn't know this when I merged the PR that added it.

I'll look into fixing this so you can use without Rails.

**Comment by tombell** [comment]
I've pushed 0.3.0 with a fix that removes the use of `cattr_accessor`. Let me know if that works!
